name: tetorica
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  chrome: any
  xml: any

dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'

transformers:
- dart_to_js_script_rewriter
